"""Initial schema

Revision ID: a40277239b7c
Revises: 
Create Date: 2025-12-30 16:29:34.570495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40277239b7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('german', sa.String(length=255), nullable=False),
    sa.Column('spanish', sa.String(length=255), nullable=False),
    sa.Column('word_class', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('example_de', sa.Text(), nullable=True),
    sa.Column('example_es', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_frequency_rank'), 'vocabulary', ['frequency_rank'], unique=False)
    op.create_index(op.f('ix_vocabulary_id'), 'vocabulary', ['id'], unique=False)
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sessions_id'), 'review_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_review_sessions_reviewed_at'), 'review_sessions', ['reviewed_at'], unique=False)
    op.create_table('user_vocabulary_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('times_wrong', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vocabulary_progress_id'), 'user_vocabulary_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_progress_next_review'), 'user_vocabulary_progress', ['next_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vocabulary_progress_next_review'), table_name='user_vocabulary_progress')
    op.drop_index(op.f('ix_user_vocabulary_progress_id'), table_name='user_vocabulary_progress')
    op.drop_table('user_vocabulary_progress')
    op.drop_index(op.f('ix_review_sessions_reviewed_at'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index(op.f('ix_vocabulary_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_frequency_rank'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
